docs: explain the importance of waiting for docker build
interledgerjs/ilp-kit-docker-compose pull request #10
Opened 2017-06-22 13:35 UTC by michielbdejong

Fixes #8.

2017-06-22 14:12 UTC, sharafian requested changes

2017-06-22 14:12 UTC, sharafian commented on README.md
> +> Log in to your ilp-kit
These should be changed to level 2 headings `##` instead of block quotes `>`.

2017-06-22 14:12 UTC, sharafian commented on README.md
> +First, wait for about 20 minutes! Until then, there will be nothing to see yet on your ilp-kit URL, or just an nginx default page.
Do you have to wait 20 minutes deploying with the docker compose, or just with Azure?

2017-06-22 17:47 UTC, michielbdejong commented on README.md
> +First, wait for about 20 minutes! Until then, there will be nothing to see yet on your ilp-kit URL, or just an nginx default page.
it might have been just 10 minutes for the docker compose instructions, I'll measure the azure time again, and change it to "up to X minutes".

2017-06-26 12:32 UTC, michielbdejong commented
Method I used now for updating:
```sh
docker pull michielbdejong/ilp-kit # created that first using the Docker Hub UI
docker tag michielbdejong/ilp-kit interledgerjs/ilp-kit:latest
cd ilp-kit-docker-compose/
ILP_DOMAIN=*** ILP_SECRET=*** ILP_CURRENCY=usd ILP_EMAIL=*** docker-compose up -d

2017-06-26 12:42 UTC, michielbdejong commented
Ah, and the currency must be upper-case, should mention that in the docs!

2017-06-26 14:29 UTC, michielbdejong commented
some more tips when running ilp-kit on azure for debugging:
```sh
sudo chown -R michiel ilp-kit-docker-compose/
```
when deploying to azure is you have to race once you know your vps’s CNAME target, to edit DNS on cloudflare or wherever you have it, to point to is before the letsencrypt container comes up

2017-07-04 15:04 UTC, sharafian approved these changes

2017-07-04 16:02 UTC, merged